### ISSUE TITLE
Delist Klayswap feeds from Baobab

### ISSUE THREAD

**Issue by martinkersner** [Bisonai/orakl-config#56]

**Comment by martinkersner** [comment]
Off-chain aggregation will be soon deployed to Baobab cluster which replaces the previous Data Feed solution. Off-chain aggregation does not connect and verify adapter hash values between adapter and aggregator, therefore it will be easier to delist Klayswap at the time of Baobab on-chain deployment.

**Comment by nick-bisonai** [comment]
removed from orakl-config
